# Arduino duemilanove
#BOARD_TAG    = atmega328 
#ARDUINO_PORT = /dev/ttyUSB0

# Arduino UNO
BOARD_TAG    = uno
ARDUINO_PORT = /dev/ttyACM0

# New kid
BOARD_TAG    = uno
ARDUINO_PORT = /dev/ttyUSB0

ARDUINO_LIBS = homeGW BMP085 SPI GreenHouseProtocol RF24 Wire Wire/utility RemoteSwitch 

include /usr/share/arduino/Arduino.mk
